CALIBRATING_MASS_GRAMS = 298.254
CLAMP_GRAMS = 63.352

CALIBRATING_MASS_10_N = CLAMP_GRAMS + CALIBRATING_MASS_GRAMS
CALIBRATING_MASS_1_N = CLAMP_GRAMS

DEFAULT_CLAMPS_DISTANCE = 8.18

PLOTS_SYMBOL = 'x'
PLOTS_SYMBOL_SIZE = 5